
CREATE TABLE TRENER
(
  ID INT PRIMARY KEY,
  IMIE VARCHAR(16) NOT NULL,
  NAZWISKO VARCHAR(32) NOT NULL
);

CREATE TABLE ARBITER
(
  ID_ARBITER SERIAL PRIMARY KEY,
  IMIE VARCHAR(16) NOT NULL,
  NAZWISKO VARCHAR(32) NOT NULL
);

CREATE TABLE LIGA
(
  ID_LIG SERIAL PRIMARY KEY,
  NAZWA VARCHAR(32) NOT NULL UNIQUE,
  NARODOWOSC VARCHAR(20) NOT NULL
);

CREATE TABLE MECZ
(
  ID_MECZ SERIAL PRIMARY KEY,
  GOSPODARZE varchar(32) not null,
  GOSCIE VARCHAR(32) NOT NULL,
  NUMER_STADION int NOT NULL,
  DATA DATE NOT NULL,
  NR_ARBITER INT NOT NULL,
  CONSTRAINT ARBITER_FK FOREIGN KEY(NR_ARBITER)
  REFERENCES ARBITER(ID_ARBITER)
);

CREATE TABLE KLUB
(
  ID_KLUB serial primary key,
  ROK_UTWORZENIA INT NOT NULL,
  KLUB_NAZWA VARCHAR(32) NOT NULL UNIQUE,
  ID_TRENER INT UNIQUE,
  ID_LIGA INT,
  id_meczu int,
  CONSTRAINT TRENER_FK FOREIGN KEY(ID_TRENER)
  REFERENCES TRENER(ID),
  CONSTRAINT LIGA_FK foreign key(id_liga)
  references LIGA(id_lig),
  CONSTRAINT mecz_FK FOREIGN KEY(id_meczu)
  references mecz(id_mecz)
);

CREATE TABLE PILKARZ
(
  ID_PILKARZ SERIAL PRIMARY KEY,
  IMIE VARCHAR(16) NOT NULL,
  NAZWISKO VARCHAR(32) NOT NULL,
  POZYCJA VARCHAR(32) NOT NULL,
  NARODOWOSC VARCHAR(32) NOT NULL,
  klub_id int,
  constraint klub_fk foreign key(klub_id)
  references klub(id_klub)
);

CREATE TABLE STADION
(
  NUMER SERIAL PRIMARY KEY,
  NAZWA VARCHAR(64),
  NALEZY_DO VARCHAR(64) not null unique,
  MIASTO VARCHAR(32) NOT NULL,
  KRAJ VARCHAR(32) NOT NULL,
  CONSTRAINT KLUB_FK FOREIGN KEY(NALEZY_DO)
  REFERENCES KLUB(KLUB_NAZWA)
);
